import type { InferInsertModel } from "drizzle-orm"

import {
  customers,
  orders,
  refundPolicies,
  refunds,
  shipments,
  tickets,
} from "@/lib/db/schema"

type NewCustomer = InferInsertModel<typeof customers>
type NewOrder = InferInsertModel<typeof orders>
type NewShipment = InferInsertModel<typeof shipments>
type NewRefundPolicy = InferInsertModel<typeof refundPolicies>
type NewRefund = InferInsertModel<typeof refunds>
type NewTicket = InferInsertModel<typeof tickets>

const createdAt = new Date("2026-08-01T09:00:00.000Z")

export const seedCustomers = [
  {
    id: "CUS-003",
    name: "Harbor Foods",
    tier: "STANDARD",
    email: "orders@harbor-foods.example",
    status: "ACTIVE",
    createdAt,
  },
  {
    id: "CUS-001",
    name: "Northstar Industries",
    tier: "GOLD",
    email: "operations@northstar.example",
    status: "ACTIVE",
    createdAt,
  },
  {
    id: "CUS-005",
    name: "Cedar Telecom",
    tier: "SILVER",
    email: "supply@cedar-telecom.example",
    status: "ACTIVE",
    createdAt,
  },
  {
    id: "CUS-006",
    name: "Beacon Aerospace",
    tier: "GOLD",
    email: "logistics@beacon-aero.example",
    status: "ACTIVE",
    createdAt,
  },
  {
    id: "CUS-002",
    name: "Meridian Health",
    tier: "GOLD",
    email: "supply@meridian-health.example",
    status: "ACTIVE",
    createdAt,
  },
  {
    id: "CUS-004",
    name: "Silverline Retail",
    tier: "SILVER",
    email: "orders@silverline.example",
    status: "ACTIVE",
    createdAt,
  },
  {
    id: "CUS-007",
    name: "Atlas Manufacturing",
    tier: "GOLD",
    email: "procurement@atlas.example",
    status: "ACTIVE",
    createdAt,
  },
  {
    id: "CUS-008",
    name: "Oakridge Education",
    tier: "STANDARD",
    email: "purchasing@oakridge-edu.example",
    status: "ACTIVE",
    createdAt,
  },
  {
    id: "CUS-009",
    name: "Bluewave Hospitality",
    tier: "SILVER",
    email: "operations@bluewave.example",
    status: "INACTIVE",
    createdAt,
  },
  {
    id: "CUS-010",
    name: "Pioneer Energy",
    tier: "STANDARD",
    email: "procurement@pioneer-energy.example",
    status: "ACTIVE",
    createdAt,
  },
] satisfies NewCustomer[]

export const seedOrders = [
  {
    id: "ORD-1024",
    customerId: "CUS-001",
    total: 420_000,
    status: "SHIPPED",
    shipmentId: "SHP-031",
    createdAt,
  },
  {
    id: "ORD-1030",
    customerId: "CUS-003",
    total: 85_000,
    status: "DELIVERED",
    shipmentId: "SHP-030",
    createdAt,
  },
  {
    id: "ORD-1031",
    customerId: "CUS-003",
    total: 120_000,
    status: "SHIPPED",
    shipmentId: "SHP-033",
    createdAt,
  },
  {
    id: "ORD-1025",
    customerId: "CUS-001",
    total: 180_000,
    status: "SHIPPED",
    shipmentId: "SHP-032",
    createdAt,
  },
  {
    id: "ORD-1045",
    customerId: "CUS-005",
    total: 210_000,
    status: "PROCESSING",
    shipmentId: "SHP-045",
    createdAt,
  },
  {
    id: "ORD-1046",
    customerId: "CUS-005",
    total: 145_000,
    status: "DELIVERED",
    shipmentId: "SHP-046",
    createdAt,
  },
  {
    id: "ORD-1047",
    customerId: "CUS-006",
    total: 510_000,
    status: "SHIPPED",
    shipmentId: "SHP-047",
    createdAt,
  },
  {
    id: "ORD-1048",
    customerId: "CUS-006",
    total: 275_000,
    status: "DELIVERED",
    shipmentId: "SHP-048",
    createdAt,
  },
  {
    id: "ORD-1042",
    customerId: "CUS-002",
    total: 250_000,
    status: "SHIPPED",
    shipmentId: "SHP-041",
    createdAt,
  },
  {
    id: "ORD-1051",
    customerId: "CUS-004",
    total: 95_000,
    status: "DELIVERED",
    shipmentId: "SHP-051",
    createdAt,
  },
  {
    id: "ORD-1050",
    customerId: "CUS-004",
    total: 320_000,
    status: "SHIPPED",
    shipmentId: "SHP-050",
    createdAt,
  },
  {
    id: "ORD-1060",
    customerId: "CUS-007",
    total: 650_000,
    status: "SHIPPED",
    shipmentId: "SHP-060",
    createdAt,
  },
  {
    id: "ORD-1070",
    customerId: "CUS-008",
    total: 76_000,
    status: "SHIPPED",
    shipmentId: "SHP-070",
    createdAt,
  },
  {
    id: "ORD-1071",
    customerId: "CUS-008",
    total: 132_000,
    status: "DELIVERED",
    shipmentId: "SHP-071",
    createdAt,
  },
  {
    id: "ORD-1080",
    customerId: "CUS-009",
    total: 188_000,
    status: "SHIPPED",
    shipmentId: "SHP-080",
    createdAt,
  },
  {
    id: "ORD-1081",
    customerId: "CUS-009",
    total: 64_000,
    status: "CANCELLED",
    shipmentId: "SHP-081",
    createdAt,
  },
  {
    id: "ORD-1090",
    customerId: "CUS-010",
    total: 225_000,
    status: "PROCESSING",
    shipmentId: "SHP-090",
    createdAt,
  },
  {
    id: "ORD-1091",
    customerId: "CUS-010",
    total: 155_000,
    status: "DELIVERED",
    shipmentId: "SHP-091",
    createdAt,
  },
  {
    id: "ORD-1092",
    customerId: "CUS-010",
    total: 340_000,
    status: "SHIPPED",
    shipmentId: "SHP-092",
    createdAt,
  },
  {
    id: "ORD-1093",
    customerId: "CUS-005",
    total: 268_000,
    status: "SHIPPED",
    shipmentId: "SHP-093",
    createdAt,
  },
  {
    id: "ORD-1094",
    customerId: "CUS-003",
    total: 48_000,
    status: "PROCESSING",
    shipmentId: "SHP-094",
    createdAt,
  },
] satisfies NewOrder[]

export const seedShipments = [
  {
    id: "SHP-031",
    orderId: "ORD-1024",
    carrier: "DHL",
    trackingNumber: "DHL-DEMO-00031",
    status: "DELAYED",
    delayDays: 4,
  },
  {
    id: "SHP-032",
    orderId: "ORD-1025",
    carrier: "FedEx",
    trackingNumber: "FDX-DEMO-00032",
    status: "IN_TRANSIT",
    delayDays: 0,
  },
  {
    id: "SHP-030",
    orderId: "ORD-1030",
    carrier: "UPS",
    trackingNumber: "UPS-DEMO-00030",
    status: "DELIVERED",
    delayDays: 0,
  },
  {
    id: "SHP-033",
    orderId: "ORD-1031",
    carrier: "DHL",
    trackingNumber: "DHL-DEMO-00033",
    status: "DELAYED",
    delayDays: 1,
  },
  {
    id: "SHP-041",
    orderId: "ORD-1042",
    carrier: "UPS",
    trackingNumber: "UPS-DEMO-00041",
    status: "DELAYED",
    delayDays: 2,
  },
  {
    id: "SHP-045",
    orderId: "ORD-1045",
    carrier: "FedEx",
    trackingNumber: "FDX-DEMO-00045",
    status: "PENDING",
    delayDays: 0,
  },
  {
    id: "SHP-046",
    orderId: "ORD-1046",
    carrier: "UPS",
    trackingNumber: "UPS-DEMO-00046",
    status: "DELIVERED",
    delayDays: 0,
  },
  {
    id: "SHP-047",
    orderId: "ORD-1047",
    carrier: "DHL",
    trackingNumber: "DHL-DEMO-00047",
    status: "IN_TRANSIT",
    delayDays: 0,
  },
  {
    id: "SHP-048",
    orderId: "ORD-1048",
    carrier: "FedEx",
    trackingNumber: "FDX-DEMO-00048",
    status: "DELIVERED",
    delayDays: 0,
  },
  {
    id: "SHP-050",
    orderId: "ORD-1050",
    carrier: "DHL",
    trackingNumber: "DHL-DEMO-00050",
    status: "DELAYED",
    delayDays: 3,
  },
  {
    id: "SHP-051",
    orderId: "ORD-1051",
    carrier: "UPS",
    trackingNumber: "UPS-DEMO-00051",
    status: "DELIVERED",
    delayDays: 0,
  },
  {
    id: "SHP-060",
    orderId: "ORD-1060",
    carrier: "FedEx",
    trackingNumber: "FDX-DEMO-00060",
    status: "DELAYED",
    delayDays: 5,
  },
  {
    id: "SHP-070",
    orderId: "ORD-1070",
    carrier: "DHL",
    trackingNumber: "DHL-DEMO-00070",
    status: "DELAYED",
    delayDays: 2,
  },
  {
    id: "SHP-071",
    orderId: "ORD-1071",
    carrier: "FedEx",
    trackingNumber: "FDX-DEMO-00071",
    status: "DELIVERED",
    delayDays: 0,
  },
  {
    id: "SHP-080",
    orderId: "ORD-1080",
    carrier: "UPS",
    trackingNumber: "UPS-DEMO-00080",
    status: "DELAYED",
    delayDays: 2,
  },
  {
    id: "SHP-081",
    orderId: "ORD-1081",
    carrier: "DHL",
    trackingNumber: "DHL-DEMO-00081",
    status: "PENDING",
    delayDays: 0,
  },
  {
    id: "SHP-090",
    orderId: "ORD-1090",
    carrier: "FedEx",
    trackingNumber: "FDX-DEMO-00090",
    status: "PENDING",
    delayDays: 0,
  },
  {
    id: "SHP-091",
    orderId: "ORD-1091",
    carrier: "UPS",
    trackingNumber: "UPS-DEMO-00091",
    status: "DELIVERED",
    delayDays: 0,
  },
  {
    id: "SHP-092",
    orderId: "ORD-1092",
    carrier: "DHL",
    trackingNumber: "DHL-DEMO-00092",
    status: "IN_TRANSIT",
    delayDays: 0,
  },
  {
    id: "SHP-093",
    orderId: "ORD-1093",
    carrier: "FedEx",
    trackingNumber: "FDX-DEMO-00093",
    status: "DELAYED",
    delayDays: 2,
  },
  {
    id: "SHP-094",
    orderId: "ORD-1094",
    carrier: "UPS",
    trackingNumber: "UPS-DEMO-00094",
    status: "PENDING",
    delayDays: 0,
  },
] satisfies NewShipment[]

export const seedRefundPolicies = [
  {
    id: "POL-GOLD",
    tier: "GOLD",
    refundPercentage: 20,
    maxAutoRefund: 100_000,
  },
  {
    id: "POL-SILVER",
    tier: "SILVER",
    refundPercentage: 10,
    maxAutoRefund: 50_000,
  },
  {
    id: "POL-STANDARD",
    tier: "STANDARD",
    refundPercentage: 5,
    maxAutoRefund: 25_000,
  },
] satisfies NewRefundPolicy[]

export const seedRefunds = [
  {
    orderId: "ORD-1030",
    amount: 4_250,
    status: "COMPLETED",
    createdAt,
  },
  {
    orderId: "ORD-1046",
    amount: 14_500,
    status: "COMPLETED",
    createdAt,
  },
  {
    orderId: "ORD-1091",
    amount: 7_750,
    status: "COMPLETED",
    createdAt,
  },
] satisfies NewRefund[]

export const seedTickets = [
  {
    id: "TKT-001",
    orderId: "ORD-1031",
    customerId: "CUS-003",
    title: "Delivery date clarification",
    status: "OPEN",
    notes: "Customer requested an updated delivery estimate.",
    updatedAt: createdAt,
  },
  {
    id: "TKT-002",
    orderId: "ORD-1046",
    customerId: "CUS-005",
    title: "Proof of delivery request",
    status: "RESOLVED",
    notes: "Proof of delivery was sent to the customer.",
    updatedAt: createdAt,
  },
  {
    id: "TKT-003",
    orderId: "ORD-1047",
    customerId: "CUS-006",
    title: "Tracking link issue",
    status: "OPEN",
    notes: "Carrier tracking link is being investigated.",
    updatedAt: createdAt,
  },
  {
    id: "TKT-004",
    orderId: "ORD-1070",
    customerId: "CUS-008",
    title: "Delayed classroom equipment",
    status: "IN_PROGRESS",
    notes: "Logistics team is coordinating with the carrier.",
    updatedAt: createdAt,
  },
  {
    id: "TKT-005",
    orderId: "ORD-1080",
    customerId: "CUS-009",
    title: "Shipment delay inquiry",
    status: "OPEN",
    notes: "Customer requested a revised arrival date.",
    updatedAt: createdAt,
  },
  {
    id: "TKT-006",
    orderId: "ORD-1091",
    customerId: "CUS-010",
    title: "Invoice copy requested",
    status: "RESOLVED",
    notes: "Invoice copy was provided.",
    updatedAt: createdAt,
  },
  {
    id: "TKT-009",
    orderId: "ORD-1024",
    customerId: "CUS-001",
    title: "Production parts delayed",
    status: "OPEN",
    notes: "Customer production schedule is at risk.",
    updatedAt: createdAt,
  },
  {
    id: "TKT-010",
    orderId: "ORD-1042",
    customerId: "CUS-002",
    title: "Cold-chain delay follow-up",
    status: "RESOLVED",
    notes: "Replacement delivery plan was confirmed.",
    updatedAt: createdAt,
  },
] satisfies NewTicket[]
